defaultBaseImage: gcr.io/distroless/static:nonroot
defaultPlatforms:
- linux/arm64

builds:
- id: telegram-delete-join-messages
  main: ./cmd/telegram-delete-join-messages
  ldflags:
  - "-s"
  - "-w"
  - "-X main.version={{.Env.BUILD_VERSION}}"